site_name: Ktisis Docs
site_url: https://sleepybnuuy.github.io/ktisis-docs/
site_description: Documentation wiki for the Ktisis GPose plugin.

repo_url: https://github.com/sleepybnuuy/ktisis-testing
repo_name: sleepybnuuy/ktitis-testing

theme:
  name: material
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
      primary: deep purple
      accent: purple
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
      primary: deep purple
      accent: purple
  logo: assets/icon2.png
  favicon: assets/icon.png

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.blocks.caption

plugins:
  - social

# any navigable new pages must be added to nav for manual sorting
nav:
  - Home: index.md
  - FAQ: faq.md
  - Posing:
    - Overlay Controls: posing/overlay.md
    - Pose Mode: posing/posemode.md
    - Inverse Kinematics: posing/ik.md
  - Actors:
    - Actor Management: actors/manage.md
    - Animation: actors/animation.md
    - Gaze Control: actors/gaze.md
    - IPC Support: actors/ipc.md
  - Scene:
    - Lighting: scene/lighting.md
    - Camera Controls: scene/camera.md
  - Windows:
    - Ktisis Workspace: windows/workspace.md
    - Actor Editor: windows/actor.md
    - Environment Editor: windows/environment.md
    - Camera Editor: windows/camera.md
    - Pose View: windows/poseview.md
    - Settings: windows/config.md
  - Guides:
    # - Migrating to v0.3: guides/migration.md
    # - GPosing Tips: guides/tips.md
    # - Lighting 101: guides/lighting.md
    # - Gizmo & Transform Usage: guides/transform.md
    # - Community Resources: guides/resources.md
    - External Tools: guides/tools.md
  - Known Issues: issues.md
  - Updates: updates.md
  - About: about.md
