site_name: Ktisis Docs
site_url: https://sleepybnuuy.github.io/ktisis-docs/
repo_url: https://github.com/sleepybnuuy/ktisis-testing
repo_name: sleepybnuuy/ktitis-testing

theme:
  name: material
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
      primary: deep purple
      accent: purple
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
      primary: deep purple
      accent: purple
  features:
    - navigation.expand
    - navigation.path
  logo: assets/icon.png
  favicon: assets/icon.png

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

# any navigable new pages must be added to nav for manual sorting
nav:
  - Home: index.md
  - FAQ: faq.md
  - Windows:
    - Workspace: windows/workspace.md
    - Actor Editor: windows/actor.md
    - Environment Editor: windows/environment.md
    - Settings: windows/config.md
